# Generated by Django 3.1.7 on 2021-02-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
