# Generated by Django 3.1.7 on 2021-02-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='title',
        ),
        migrations.AddField(
            model_name='alert',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alert',
            name='direction',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='UP', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], default='DOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='alert',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.currency'),
        ),
    ]
